# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-07 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('village', models.CharField(max_length=255)),
                ('crop_grown', models.CharField(blank=True, max_length=255)),
                ('sowing_date', models.DateTimeField(auto_now_add=True)),
                ('is_crop_grown', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('farmer_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('language', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_after_sowing', models.IntegerField()),
                ('Fertiliser', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField()),
                ('quantity_unit', models.CharField(choices=[('ton', 'Ton'), ('kg', 'Kilograms'), ('g', 'grams'), ('L', 'litres'), ('mL', 'millitres')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='farmer_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Farmers'),
        ),
    ]
