# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-08 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Farmers',
            new_name='Farmer',
        ),
        migrations.RenameModel(
            old_name='Schedule_details',
            new_name='Schedule_detail',
        ),
    ]
