# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-08 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0002_auto_20190408_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='is_crop_grown',
        ),
        migrations.AlterField(
            model_name='farm',
            name='sowing_date',
            field=models.DateTimeField(),
        ),
    ]
