# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-08 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0003_auto_20190408_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='farmer_detail',
            new_name='farmer',
        ),
    ]
