# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-08 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0004_auto_20190408_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_detail',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
