# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-08 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0005_schedule_detail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
